### ISSUE TITLE
Request: Add Blockly support 

### ISSUE THREAD

**Issue by peterparnes** [incognite-lab/Pepper-Controller#1]
Request: A really nice development would be to add Blockly where kids (of all ages) could program Pepper using graphical programming and have it deployed in real-time to the robot. Blockly->Python is there but I am unsure if it is Python2 or 3.

**Comment by michalvavrecka** [comment]
Dear Peter,

this software is designed for programming Pepper robot from Python keeping in mind all advantages of this approach. If you would like to program Pepper with GUI, there are Choreographe and PandaSuite suitable for this task. Especially PandaSuite is very similar to Blocky type of programming.
