### ISSUE TITLE
can not stopped robot.listen()

### ISSUE THREAD

**Issue by hieule88** [incognite-lab/Pepper-Controller#2]
How can I stop the Recording when using .listen() ? I tried your ask_wikipedia() function but it also was not be stopped

**Comment by michtesar** [comment]
I would recommend to spin `listen()` method in another thread while main thread monitors [event ](http://doc.aldebaran.com/2-5/naoqi/audio/alspeechrecognition-api.html#ALSpeechRecognition/ActiveListening) for status `ListenOff` or `EndOfProcess` (not sure which one). Based on NaoQi implementation which I don’t remember it’s either terminating the listening thread or calling some other method to stop listening. For such method please consult [NaoQi API docs](http://doc.aldebaran.com/2-5/naoqi/index.html).

**Comment by hieule88** [comment]
I wanna embed my python code to peppers' system (not just send the command to pepper but set up pepper life by python). How can I do it

**Comment by michtesar** [comment]
Use Choreography to write Python nodes or make a binary package for the robot (I highly discourage you to do the second mentioned, because it is deprecated functionality).

**Comment by hieule88** [comment]
Thank you! I'm trying to check how much memories are available in pepper. How can I access to see Pepper as a folder ?

**Comment by michalvavrecka** [comment]
This question is dedicated to Choreographe and Naoqi software. Refer to the Aldebaran documentation for tutorials - http://doc.aldebaran.com/2-5/index_dev_guide.html . The easiest way to connect to internal storage of Pepper is via SSH.

**Comment by hieule88** [comment]
I'm using table_service.showWebview() method but it is HEAD method as default, how can I change it to GET method ?

**Comment by michtesar** [comment]
@hieule88 not sure if the HTTP request methods has something to do with the SDK, but take a look at the docs with the code [example](http://doc.aldebaran.com/2-5/naoqi/core/altabletservice-api.html#altabletservice-showwebview2) that might help.

**Comment by gabinsane** [comment]
I consider this issue resolved. Please make a new issue if you have any further questions. Thanks!
