### ISSUE TITLE
Invalid syntax when trying to import Pepper

### ISSUE THREAD

**Issue by ghost** [incognite-lab/Pepper-Controller#3]
After following the readme and running `from pepper.robot import Pepper`, I receive an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pepper/robot.py", line 18, in <module>
    import speech_recognition
  File "/home/eli/.local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 1513
    endpoint = f"https://api.assemblyai.com/v2/transcript/{transciption_id}"
                                                                           ^
SyntaxError: invalid syntax
```

This is on Ubuntu 20.04 wsl and python 2.7 as per the guide.

**Comment by SirRanger** [comment]
I have the same Error on Ubuntu 16.04 and Python 2.7
Any Updates on this?

**Comment by gabinsane** [comment]
Hi, what version of the SpeechRecognition package are you using? 

You can try the following:

```
pip uninstall speechrecognition
pip install speechrecognition==3.8.1
```
(Use pip2 if not using conda or a virtual environment)
The 3.8.1 version does not produce any error on my Ubuntu 18.04 and Python 2.7. Please let me know if that works for you.

**Comment by SirRanger** [comment]
That worked Thank you. Having no trouble to connect. I opened a new Bug for it.

**Comment by gabinsane** [comment]
Ok, closing this issue. I will update the requirements with the required speech reco package version
