### ISSUE TITLE
Connection to Pepper failing

### ISSUE THREAD

**Issue by SirRanger** [incognite-lab/Pepper-Controller#5]
**System:**

- Ubuntu 20.04
- Python 2.7
- Pepper Controller 2.0.1
- Pepper robot NAOqi 2.9.5.172

If i try to connect, the connect button gets stuck and nothing i happening. Pepper controller is then stuck for minutes. I have to kill it by closing the terminal window.
The IP is correct and Port to. If i put a wrong port number, i get an error connect: Connection refused.
If i put the right one in i dont get an output in Terminal. 

Is there a maximum supported version of pepper naoqi version?

**Comment by gabinsane** [comment]
Hi, you need NAOqi 2.5, the link is in the README. We cannot test with NAOqi > 2.5 as we have an older robot. 
To specifically test if you are able to connect to the robot (and that there is no other issue within the GUI), you can run the minimal code:

```
import qi
session = qi.Session()
session.connect("tcp://1.1.1.1:9559") # replace "1.1.1.1" with your robot's IP address
```

**Comment by SirRanger** [comment]
Thank you.

Do you mean this: _Install Pepper SDK 2.5.10 library for Python 2.7 from https://www.softbankrobotics.com/emea/en/support/pepper-naoqi-2-9/downloads-softwares_

Im using this python version. 
I did not found a link to an older os version image to flash on pepper, if you meant this.

**Comment by gabinsane** [comment]
Ok, but you stated that you have Pepper robot with NAOqi 2.9.5. - this is not going to work with the 2.5 NAOqi library. I am not even sure that your robot version supports python programming anymore as I cannot find any Python SDK for this version online, and 2.9.5 is officially named an "Android version". Cannot help with that, sorry

**Comment by SirRanger** [comment]
Im now downgrading Pepper to NAOqi 2.5.10. 

This version the one you used? I will try it with this one.
Thanks for you fast reply. You help me very much :)

**Comment by gabinsane** [comment]
Yes, 2.5.10 is the right one. However, I am afraid that a downgrade from 2.9.5 to 2.5.10 is not possible, see https://support.old.unitedrobotics.group/en/support/discussions/topics/80000658264. Anyway, good luck with your work :)
