### ISSUE TITLE
Inquiry on software developed for Pepper

### ISSUE THREAD

**Issue by PhilipAmadasun** [incognite-lab/Pepper-Controller#6]
Would any of the developers of this Pepper-Controller repo happen to know about the Robot Operating System (ROS) packages developed for the pepper robot? I ask here because it is hard to find resources of knowledge focused on the pepper and NAO robots,please forgive that this line of inquiry is not directly related to the Pepper-Controller repo itself. 

If knowledge of the ROS packages is known, would the ROS (melodic specifically)  packages work with a Naoqi OS of version 2.5.7.1 (can't recall if it's .1) or so?

**Comment by michalvavrecka** [comment]
There are several project connecting naoqi with ROS. We were able to test it on Pepper robot, but never developed any code for this. TYou can test it here - https://github.com/awesomebytes/pepper_os
