### ISSUE TITLE
yolact suppsoed to be ran in python3 or 2?

### ISSUE THREAD

**Issue by PhilipAmadasun** [incognite-lab/Pepper-Controller#8]
I'm trying to run pepper.yo.py in python2 but get a  syntax error:
```
    from yolact import Yolact
  File "/home/philip/pepper_robot/Pepper-Controller/pepper_yolact/ciircgym/yolact_vision/yolact.py", line 311
    def forward(self, convouts:List[torch.Tensor]):
                              ^
SyntaxError: invalid syntax
```
This seems like a syntax error caused by the python interpreter. I think the version of python I'm trying to use for execution may be to blame?

**Comment by gabinsane** [comment]
Hi, Yolact is supposed to be used with Python 3.7. I recommend installing the conda environment in pepper_yolact/environment.yml. Then please follow the Yolact README https://github.com/incognite-lab/Pepper-Controller/tree/main/pepper_yolact

**Comment by PhilipAmadasun** [comment]
@gabinsane  Is it a specific sub-version of 3.7? like 3.7.1, or 3.7.9 and so on? Or any  version of 3.7?

**Comment by gabinsane** [comment]
I am closing this issue as there are no more questions

**Comment by gabinsane** [comment]
I am closing this issue as there are no more questions
